crws crw_all (ps p, crws cs);
crws crw_deall (crws cs);
crws wh (crws cs);
crws wb (crws cs);
crws oct (crws cs);
crws mogst (crws cs);
crws mugst (crws cs);
crws tf (crws cs);
crws ugname (crws cs);
crws chksum (crws cs);
